CREATE INDEX idx_filter_17crash ON '2017crash'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_17crsh_flags ON '2017crsh_flags'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_17person ON '2017person'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_17vehicle ON '2017vehicle'(CRSHNMBR, CNTYCODE, CRSHSVR);

CREATE INDEX idx_filter_18crash ON '2018crash'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_18crsh_flags ON '2018crsh_flags'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_18person ON '2018person'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_18vehicle ON '2018vehicle'(CRSHNMBR, CNTYCODE, CRSHSVR);

CREATE INDEX idx_filter_19crash ON '2019crash'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_19crsh_flags ON '2019crsh_flags'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_19person ON '2019person'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_19vehicle ON '2019vehicle'(CRSHNMBR, CNTYCODE, CRSHSVR);

CREATE INDEX idx_filter_20crash ON '2020crash'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_20crsh_flags ON '2020crsh_flags'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_20person ON '2020person'(CRSHNMBR, CNTYCODE, CRSHSVR);
CREATE INDEX idx_filter_20vehicle ON '2020vehicle'(CRSHNMBR, CNTYCODE, CRSHSVR);